###

# curl -X POST http://localhost:8080/students -H"Content-Type: application/json" -d '{"id":1, "name": "manty"}'
POST http://localhost:8080/students
Content-Type: application/json

{
"id": 1,
"name": "manty"
}

###

# curl -X GET http://localhost:8080/students/1
GET http://localhost:8080/students/1

###

